CMD_ATTR = '__cmd'
CALLBACK_ATTR = '__callback'
JOB_ATTR_DAILY = '__schedule'
METHOD_HAS_USER_ATTR = '__user_param'
METHOD_HAS_ROOM_ATTR = '__room_param'
METHOD_HAS_CALLBACK_ID_ATTR = '__message_param'
METHOD_HAS_ACTIONS_ATTR = '__actions_param'
METHOD_HAS_CHANNEL_ATTR = '__channel_param'
